steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'eu.gcr.io/${_GCP_PROJECT_ID}/base_image_${_IMAGE_NAME}:${_IMAGE_TAG}', '-f', './components/base_images/${_IMAGE_NAME}/Dockerfile', '.']
options:
  logging: CLOUD_LOGGING_ONLY
images: ['eu.gcr.io/${_GCP_PROJECT_ID}/base_image_${_IMAGE_NAME}:${_IMAGE_TAG}']